#!/usr/bin/env node
/**
 * Generate version from git for Erenshor Logs project.
 * Format: YYYY.M.D+COMMITHASH (semver-compliant CalVer)
 * Writes to: web/src/lib/version.ts
 */

import { execSync } from 'child_process';
import { writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = join(__dirname, '..');
const OUTPUT_FILE = join(PROJECT_ROOT, 'web/src/lib/version.ts');

function getVersion() {
  try {
    // Get version from git (use + for build metadata, not - for pre-release)
    const gitVersion = execSync(
      'git log -1 --format="%cd+%h" --date=format:"%Y.%m.%d"',
      { encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'], cwd: PROJECT_ROOT }
    )
      .trim()
      // Remove leading zeros from month/day for semver compliance
      .replace(/\.0(\d)/g, '.$1');

    // Check for dirty working tree
    const gitStatus = execSync('git status --porcelain', {
      encoding: 'utf8',
      stdio: ['pipe', 'pipe', 'pipe'],
      cwd: PROJECT_ROOT,
    }).trim();

    const isDirty = gitStatus.length > 0;

    if (isDirty) {
      const timestamp = new Date()
        .toISOString()
        .replace(/[-:]/g, '')
        .replace(/\..+/, '')
        .replace('T', '-');
      return `${gitVersion}-dirty-${timestamp}`;
    }

    return gitVersion;
  } catch (error) {
    // Fallback: use timestamp
    console.warn('⚠️  Git not available, using fallback version');
    const now = new Date();
    const date = now.toISOString().split('T')[0].replace(/-/g, '');
    const time = now.toISOString().split('T')[1].split('.')[0].replace(/:/g, '');
    return `0.0.0-${date}-${time}`;
  }
}

function main() {
  const version = getVersion();

  const content = `// This file is auto-generated by scripts/generate-version.js
// Do not edit manually - changes will be overwritten on next build

export const VERSION = '${version}';
`;

  // Ensure directory exists
  mkdirSync(dirname(OUTPUT_FILE), { recursive: true });

  writeFileSync(OUTPUT_FILE, content, 'utf8');
  console.log(`✓ Generated version: ${version}`);
}

main();
